// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package memory

import (
	"github.com/Remrinrin/idol-memory-api-go/api/memory"
)

type ControllerV1 struct{}

func NewV1() memory.IMemoryV1 {
	return &ControllerV1{}
}
