// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Remrinrin/idol-memory-api-go/internal/dao/internal"
)

// idolIdolGroupsDao is the data access object for the table idol_groups.
// You can define custom methods on it to extend its functionality as needed.
type idolIdolGroupsDao struct {
	*internal.IdolIdolGroupsDao
}

var (
	// IdolIdolGroups is a globally accessible object for table idol_groups operations.
	IdolIdolGroups = idolIdolGroupsDao{internal.NewIdolIdolGroupsDao()}
)

// Add your custom methods and functionality below.
