// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Remrinrin/idol-memory-api-go/internal/dao/internal"
)

// idolIdolSocialsDao is the data access object for the table idol_socials.
// You can define custom methods on it to extend its functionality as needed.
type idolIdolSocialsDao struct {
	*internal.IdolIdolSocialsDao
}

var (
	// IdolIdolSocials is a globally accessible object for table idol_socials operations.
	IdolIdolSocials = idolIdolSocialsDao{internal.NewIdolIdolSocialsDao()}
)

// Add your custom methods and functionality below.
