// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Remrinrin/idol-memory-api-go/internal/dao/internal"
)

// idolIdolsDao is the data access object for the table idols.
// You can define custom methods on it to extend its functionality as needed.
type idolIdolsDao struct {
	*internal.IdolIdolsDao
}

var (
	// IdolIdols is a globally accessible object for table idols operations.
	IdolIdols = idolIdolsDao{internal.NewIdolIdolsDao()}
)

// Add your custom methods and functionality below.
